//------------------------------------------------------------------------------
// <auto-generated>
//     Deze code is gegenereerd met een hulpprogramma.
//     Runtime-versie:2.0.50727.5485
//
//     Als u wijzigingen aanbrengt in dit bestand, kan dit onjuist gedrag veroorzaken wanneer
//     de code wordt gegenereerd.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://www.clarin.eu/cmd/", IsNullable=false)]
public partial class CMD {
    
    private CMDHeader headerField;
    
    private CMDResources resourcesField;
    
    private CMDComponents componentsField;
    
    private string cMDVersionField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    public CMD() {
        this.cMDVersionField = "1.1";
    }
    
    /// <opmerkingen/>
    public CMDHeader Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResources Resources {
        get {
            return this.resourcesField;
        }
        set {
            this.resourcesField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponents Components {
        get {
            return this.componentsField;
        }
        set {
            this.componentsField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CMDVersion {
        get {
            return this.cMDVersionField;
        }
        set {
            this.cMDVersionField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeader {
    
    private CMDHeaderMdCreator[] mdCreatorField;
    
    private CMDHeaderMdCreationDate mdCreationDateField;
    
    private CMDHeaderMdSelfLink mdSelfLinkField;
    
    private CMDHeaderMdProfile mdProfileField;
    
    private CMDHeaderMdCollectionDisplayName mdCollectionDisplayNameField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("MdCreator")]
    public CMDHeaderMdCreator[] MdCreator {
        get {
            return this.mdCreatorField;
        }
        set {
            this.mdCreatorField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDHeaderMdCreationDate MdCreationDate {
        get {
            return this.mdCreationDateField;
        }
        set {
            this.mdCreationDateField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDHeaderMdSelfLink MdSelfLink {
        get {
            return this.mdSelfLinkField;
        }
        set {
            this.mdSelfLinkField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDHeaderMdProfile MdProfile {
        get {
            return this.mdProfileField;
        }
        set {
            this.mdProfileField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDHeaderMdCollectionDisplayName MdCollectionDisplayName {
        get {
            return this.mdCollectionDisplayNameField;
        }
        set {
            this.mdCollectionDisplayNameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeaderMdCreator {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeaderMdCreationDate {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private System.DateTime valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="date")]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeaderMdSelfLink {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeaderMdProfile {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDHeaderMdCollectionDisplayName {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResources {
    
    private CMDResourcesResourceProxyList resourceProxyListField;
    
    private CMDResourcesJournalFileProxyList journalFileProxyListField;
    
    private CMDResourcesResourceRelationList resourceRelationListField;
    
    private CMDResourcesIsPartOfList isPartOfListField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    public CMDResourcesResourceProxyList ResourceProxyList {
        get {
            return this.resourceProxyListField;
        }
        set {
            this.resourceProxyListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesJournalFileProxyList JournalFileProxyList {
        get {
            return this.journalFileProxyListField;
        }
        set {
            this.journalFileProxyListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesResourceRelationList ResourceRelationList {
        get {
            return this.resourceRelationListField;
        }
        set {
            this.resourceRelationListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesIsPartOfList IsPartOfList {
        get {
            return this.isPartOfListField;
        }
        set {
            this.isPartOfListField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceProxyList {
    
    private CMDResourcesResourceProxyListResourceProxy[] resourceProxyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceProxy")]
    public CMDResourcesResourceProxyListResourceProxy[] ResourceProxy {
        get {
            return this.resourceProxyField;
        }
        set {
            this.resourceProxyField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceProxyListResourceProxy {
    
    private CMDResourcesResourceProxyListResourceProxyResourceType resourceTypeField;
    
    private CMDResourcesResourceProxyListResourceProxyResourceRef resourceRefField;
    
    private string idField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    public CMDResourcesResourceProxyListResourceProxyResourceType ResourceType {
        get {
            return this.resourceTypeField;
        }
        set {
            this.resourceTypeField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesResourceProxyListResourceProxyResourceRef ResourceRef {
        get {
            return this.resourceRefField;
        }
        set {
            this.resourceRefField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceProxyListResourceProxyResourceType {
    
    private string mimetypeField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private Resourcetype_simple valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string mimetype {
        get {
            return this.mimetypeField;
        }
        set {
            this.mimetypeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public Resourcetype_simple Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.clarin.eu/cmd/")]
public enum Resourcetype_simple {
    
    /// <opmerkingen/>
    Metadata,
    
    /// <opmerkingen/>
    Resource,
    
    /// <opmerkingen/>
    SearchService,
    
    /// <opmerkingen/>
    SearchPage,
    
    /// <opmerkingen/>
    LandingPage,
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceProxyListResourceProxyResourceRef {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesJournalFileProxyList {
    
    private CMDResourcesJournalFileProxyListJournalFileProxy[] journalFileProxyField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("JournalFileProxy")]
    public CMDResourcesJournalFileProxyListJournalFileProxy[] JournalFileProxy {
        get {
            return this.journalFileProxyField;
        }
        set {
            this.journalFileProxyField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesJournalFileProxyListJournalFileProxy {
    
    private CMDResourcesJournalFileProxyListJournalFileProxyJournalFileRef journalFileRefField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    public CMDResourcesJournalFileProxyListJournalFileProxyJournalFileRef JournalFileRef {
        get {
            return this.journalFileRefField;
        }
        set {
            this.journalFileRefField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesJournalFileProxyListJournalFileProxyJournalFileRef {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceRelationList {
    
    private CMDResourcesResourceRelationListResourceRelation[] resourceRelationField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("ResourceRelation")]
    public CMDResourcesResourceRelationListResourceRelation[] ResourceRelation {
        get {
            return this.resourceRelationField;
        }
        set {
            this.resourceRelationField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceRelationListResourceRelation {
    
    private CMDResourcesResourceRelationListResourceRelationRelationType relationTypeField;
    
    private CMDResourcesResourceRelationListResourceRelationRes1 res1Field;
    
    private CMDResourcesResourceRelationListResourceRelationRes2 res2Field;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    public CMDResourcesResourceRelationListResourceRelationRelationType RelationType {
        get {
            return this.relationTypeField;
        }
        set {
            this.relationTypeField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesResourceRelationListResourceRelationRes1 Res1 {
        get {
            return this.res1Field;
        }
        set {
            this.res1Field = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDResourcesResourceRelationListResourceRelationRes2 Res2 {
        get {
            return this.res2Field;
        }
        set {
            this.res2Field = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceRelationListResourceRelationRelationType {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceRelationListResourceRelationRes1 {
    
    private string refField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesResourceRelationListResourceRelationRes2 {
    
    private string refField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesIsPartOfList {
    
    private CMDResourcesIsPartOfListIsPartOf[] isPartOfField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("IsPartOf")]
    public CMDResourcesIsPartOfListIsPartOf[] IsPartOf {
        get {
            return this.isPartOfField;
        }
        set {
            this.isPartOfField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDResourcesIsPartOfListIsPartOf {
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute(DataType="anyURI")]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponents {
    
    private CMDComponentsSUBTIEL sUBTIELField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIEL SUBTIEL {
        get {
            return this.sUBTIELField;
        }
        set {
            this.sUBTIELField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIEL {
    
    private CMDComponentsSUBTIELMovie movieField;
    
    private CMDComponentsSUBTIELRelease releaseField;
    
    private CMDComponentsSUBTIELSubtitle subtitleField;
    
    private string refField;
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovie Movie {
        get {
            return this.movieField;
        }
        set {
            this.movieField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELRelease Release {
        get {
            return this.releaseField;
        }
        set {
            this.releaseField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitle Subtitle {
        get {
            return this.subtitleField;
        }
        set {
            this.subtitleField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovie {
    
    private string movieIdField;
    
    private string nameField;
    
    private string yearField;
    
    private string imdbIdField;
    
    private string kindField;
    
    private string runtimeField;
    
    private string ratedField;
    
    private string releasedField;
    
    private string plotField;
    
    private string awardsField;
    
    private float imdbRatingField;
    
    private int imdbVotesField;
    
    private CMDComponentsSUBTIELMovieAltNameList altNameListField;
    
    private CMDComponentsSUBTIELMovieSeries seriesField;
    
    private CMDComponentsSUBTIELMovieLanguageList languageListField;
    
    private CMDComponentsSUBTIELMovieCountryList countryListField;
    
    private CMDComponentsSUBTIELMovieGenreList genreListField;
    
    private CMDComponentsSUBTIELMovieDirectorList directorListField;
    
    private CMDComponentsSUBTIELMovieWriterList writerListField;
    
    private CMDComponentsSUBTIELMovieActorList actorListField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovie() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235456";
    }
    
    /// <opmerkingen/>
    public string MovieId {
        get {
            return this.movieIdField;
        }
        set {
            this.movieIdField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <opmerkingen/>
    public string ImdbId {
        get {
            return this.imdbIdField;
        }
        set {
            this.imdbIdField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Kind {
        get {
            return this.kindField;
        }
        set {
            this.kindField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Runtime {
        get {
            return this.runtimeField;
        }
        set {
            this.runtimeField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Rated {
        get {
            return this.ratedField;
        }
        set {
            this.ratedField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Released {
        get {
            return this.releasedField;
        }
        set {
            this.releasedField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Plot {
        get {
            return this.plotField;
        }
        set {
            this.plotField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Awards {
        get {
            return this.awardsField;
        }
        set {
            this.awardsField = value;
        }
    }
    
    /// <opmerkingen/>
    public float imdbRating {
        get {
            return this.imdbRatingField;
        }
        set {
            this.imdbRatingField = value;
        }
    }
    
    /// <opmerkingen/>
    public int imdbVotes {
        get {
            return this.imdbVotesField;
        }
        set {
            this.imdbVotesField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieAltNameList AltNameList {
        get {
            return this.altNameListField;
        }
        set {
            this.altNameListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieSeries Series {
        get {
            return this.seriesField;
        }
        set {
            this.seriesField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieLanguageList LanguageList {
        get {
            return this.languageListField;
        }
        set {
            this.languageListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieCountryList CountryList {
        get {
            return this.countryListField;
        }
        set {
            this.countryListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieGenreList GenreList {
        get {
            return this.genreListField;
        }
        set {
            this.genreListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieDirectorList DirectorList {
        get {
            return this.directorListField;
        }
        set {
            this.directorListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieWriterList WriterList {
        get {
            return this.writerListField;
        }
        set {
            this.writerListField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieActorList ActorList {
        get {
            return this.actorListField;
        }
        set {
            this.actorListField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieAltNameList {
    
    private string[] altNameField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieAltNameList() {
        this.componentIdField = "clarin.eu:cr1:c_1456409483197";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("AltName")]
    public string[] AltName {
        get {
            return this.altNameField;
        }
        set {
            this.altNameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieSeries {
    
    private CMDComponentsSUBTIELMovieSeriesSeason seasonField;
    
    private CMDComponentsSUBTIELMovieSeriesEpisode episodeField;
    
    private string parentImdbIdField;
    
    private string refField;
    
    private string nameField;
    
    private string rootNameField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieSeries() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235454";
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieSeriesSeason Season {
        get {
            return this.seasonField;
        }
        set {
            this.seasonField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELMovieSeriesEpisode Episode {
        get {
            return this.episodeField;
        }
        set {
            this.episodeField = value;
        }
    }
    
    /// <opmerkingen/>
    public string ParentImdbId {
        get {
            return this.parentImdbIdField;
        }
        set {
            this.parentImdbIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string RootName {
        get {
            return this.rootNameField;
        }
        set {
            this.rootNameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieSeriesSeason {
    
    private string nameField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieSeriesEpisode {
    
    private string nameField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieLanguageList {
    
    private CMDComponentsSUBTIELMovieLanguageListLanguage[] languageField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieLanguageList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534549";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Language")]
    public CMDComponentsSUBTIELMovieLanguageListLanguage[] Language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieLanguageListLanguage {
    
    private string languageIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string LanguageId {
        get {
            return this.languageIdField;
        }
        set {
            this.languageIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieCountryList {
    
    private CMDComponentsSUBTIELMovieCountryListCountry[] countryField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieCountryList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534550";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Country")]
    public CMDComponentsSUBTIELMovieCountryListCountry[] Country {
        get {
            return this.countryField;
        }
        set {
            this.countryField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieCountryListCountry {
    
    private string countryIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string CountryId {
        get {
            return this.countryIdField;
        }
        set {
            this.countryIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieGenreList {
    
    private CMDComponentsSUBTIELMovieGenreListGenre[] genreField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieGenreList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534551";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Genre")]
    public CMDComponentsSUBTIELMovieGenreListGenre[] Genre {
        get {
            return this.genreField;
        }
        set {
            this.genreField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieGenreListGenre {
    
    private string genreIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string GenreId {
        get {
            return this.genreIdField;
        }
        set {
            this.genreIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieDirectorList {
    
    private CMDComponentsSUBTIELMovieDirectorListDirector[] directorField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieDirectorList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534552";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Director")]
    public CMDComponentsSUBTIELMovieDirectorListDirector[] Director {
        get {
            return this.directorField;
        }
        set {
            this.directorField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieDirectorListDirector {
    
    private string directorIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string DirectorId {
        get {
            return this.directorIdField;
        }
        set {
            this.directorIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieWriterList {
    
    private CMDComponentsSUBTIELMovieWriterListWriter[] writerField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieWriterList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534553";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Writer")]
    public CMDComponentsSUBTIELMovieWriterListWriter[] Writer {
        get {
            return this.writerField;
        }
        set {
            this.writerField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieWriterListWriter {
    
    private string writerIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string WriterId {
        get {
            return this.writerIdField;
        }
        set {
            this.writerIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieActorList {
    
    private CMDComponentsSUBTIELMovieActorListActor[] actorField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELMovieActorList() {
        this.componentIdField = "clarin.eu:cr1:c_1455633534554";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Actor")]
    public CMDComponentsSUBTIELMovieActorListActor[] Actor {
        get {
            return this.actorField;
        }
        set {
            this.actorField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELMovieActorListActor {
    
    private string actorIdField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ActorId {
        get {
            return this.actorIdField;
        }
        set {
            this.actorIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELRelease {
    
    private string nameField;
    
    private string countryCodeField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELRelease() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235455";
    }
    
    /// <opmerkingen/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitle {
    
    private string subtitleIdField;
    
    private string languageAvailableField;
    
    private string languageCodeField;
    
    private string targetCountryField;
    
    private string dateField;
    
    private string textHashField;
    
    private CMDComponentsSUBTIELSubtitleStatusInfo statusInfoField;
    
    private CMDComponentsSUBTIELSubtitleStatistics statisticsField;
    
    private CMDComponentsSUBTIELSubtitleLicense licenseField;
    
    private CMDComponentsSUBTIELSubtitleAuthor authorField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELSubtitle() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235457";
    }
    
    /// <opmerkingen/>
    public string SubtitleId {
        get {
            return this.subtitleIdField;
        }
        set {
            this.subtitleIdField = value;
        }
    }
    
    /// <opmerkingen/>
    public string languageAvailable {
        get {
            return this.languageAvailableField;
        }
        set {
            this.languageAvailableField = value;
        }
    }
    
    /// <opmerkingen/>
    public string languageCode {
        get {
            return this.languageCodeField;
        }
        set {
            this.languageCodeField = value;
        }
    }
    
    /// <opmerkingen/>
    public string targetCountry {
        get {
            return this.targetCountryField;
        }
        set {
            this.targetCountryField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Date {
        get {
            return this.dateField;
        }
        set {
            this.dateField = value;
        }
    }
    
    /// <opmerkingen/>
    public string textHash {
        get {
            return this.textHashField;
        }
        set {
            this.textHashField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitleStatusInfo StatusInfo {
        get {
            return this.statusInfoField;
        }
        set {
            this.statusInfoField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitleStatistics Statistics {
        get {
            return this.statisticsField;
        }
        set {
            this.statisticsField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitleLicense License {
        get {
            return this.licenseField;
        }
        set {
            this.licenseField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitleAuthor Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleStatusInfo {
    
    private CMDComponentsSUBTIELSubtitleStatusInfoSimilar[] similarField;
    
    private CMDComponentsSUBTIELSubtitleStatusInfoEvidence[] evidenceField;
    
    private string refField;
    
    private string linkField;
    
    private string statusField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELSubtitleStatusInfo() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235464";
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Similar")]
    public CMDComponentsSUBTIELSubtitleStatusInfoSimilar[] Similar {
        get {
            return this.similarField;
        }
        set {
            this.similarField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlElementAttribute("Evidence")]
    public CMDComponentsSUBTIELSubtitleStatusInfoEvidence[] Evidence {
        get {
            return this.evidenceField;
        }
        set {
            this.evidenceField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string link {
        get {
            return this.linkField;
        }
        set {
            this.linkField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleStatusInfoSimilar {
    
    private int similarIdField;
    
    private bool similarIdFieldSpecified;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SimilarId {
        get {
            return this.similarIdField;
        }
        set {
            this.similarIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool SimilarIdSpecified {
        get {
            return this.similarIdFieldSpecified;
        }
        set {
            this.similarIdFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleStatusInfoEvidence {
    
    private int evidenceIdField;
    
    private bool evidenceIdFieldSpecified;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int EvidenceId {
        get {
            return this.evidenceIdField;
        }
        set {
            this.evidenceIdField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool EvidenceIdSpecified {
        get {
            return this.evidenceIdFieldSpecified;
        }
        set {
            this.evidenceIdFieldSpecified = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleStatistics {
    
    private int nWordsField;
    
    private int nSentencesField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELSubtitleStatistics() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235459";
    }
    
    /// <opmerkingen/>
    public int nWords {
        get {
            return this.nWordsField;
        }
        set {
            this.nWordsField = value;
        }
    }
    
    /// <opmerkingen/>
    public int nSentences {
        get {
            return this.nSentencesField;
        }
        set {
            this.nSentencesField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleLicense {
    
    private string licenseCodeField;
    
    private string licenseTypeField;
    
    private string licenseDetailsField;
    
    private string licenseDateField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELSubtitleLicense() {
        this.componentIdField = "clarin.eu:cr1:c_1328259700915";
    }
    
    /// <opmerkingen/>
    public string LicenseCode {
        get {
            return this.licenseCodeField;
        }
        set {
            this.licenseCodeField = value;
        }
    }
    
    /// <opmerkingen/>
    public string LicenseType {
        get {
            return this.licenseTypeField;
        }
        set {
            this.licenseTypeField = value;
        }
    }
    
    /// <opmerkingen/>
    public string LicenseDetails {
        get {
            return this.licenseDetailsField;
        }
        set {
            this.licenseDetailsField = value;
        }
    }
    
    /// <opmerkingen/>
    public string LicenseDate {
        get {
            return this.licenseDateField;
        }
        set {
            this.licenseDateField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleAuthor {
    
    private string nameField;
    
    private string pseudonymField;
    
    private string userIDField;
    
    private string userClassField;
    
    private string sexField;
    
    private string ageField;
    
    private string motherTongueField;
    
    private CMDComponentsSUBTIELSubtitleAuthorResidencePlace residencePlaceField;
    
    private string refField;
    
    private string componentIdField;
    
    public CMDComponentsSUBTIELSubtitleAuthor() {
        this.componentIdField = "clarin.eu:cr1:c_1454489235453";
    }
    
    /// <opmerkingen/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Pseudonym {
        get {
            return this.pseudonymField;
        }
        set {
            this.pseudonymField = value;
        }
    }
    
    /// <opmerkingen/>
    public string UserID {
        get {
            return this.userIDField;
        }
        set {
            this.userIDField = value;
        }
    }
    
    /// <opmerkingen/>
    public string UserClass {
        get {
            return this.userClassField;
        }
        set {
            this.userClassField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Sex {
        get {
            return this.sexField;
        }
        set {
            this.sexField = value;
        }
    }
    
    /// <opmerkingen/>
    public string Age {
        get {
            return this.ageField;
        }
        set {
            this.ageField = value;
        }
    }
    
    /// <opmerkingen/>
    public string MotherTongue {
        get {
            return this.motherTongueField;
        }
        set {
            this.motherTongueField = value;
        }
    }
    
    /// <opmerkingen/>
    public CMDComponentsSUBTIELSubtitleAuthorResidencePlace ResidencePlace {
        get {
            return this.residencePlaceField;
        }
        set {
            this.residencePlaceField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREFS")]
    public string @ref {
        get {
            return this.refField;
        }
        set {
            this.refField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
    public string ComponentId {
        get {
            return this.componentIdField;
        }
        set {
            this.componentIdField = value;
        }
    }
}

/// <opmerkingen/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.clarin.eu/cmd/")]
public partial class CMDComponentsSUBTIELSubtitleAuthorResidencePlace {
    
    private string countryCodeField;
    
    private string townField;
    
    private string valueField;
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string countryCode {
        get {
            return this.countryCodeField;
        }
        set {
            this.countryCodeField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Town {
        get {
            return this.townField;
        }
        set {
            this.townField = value;
        }
    }
    
    /// <opmerkingen/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
